import {
  LayoutDashboard,
  Globe2,
  Factory,
  BarChart3,
  Cpu,
  MapPin,
  Search,
  Bell,
  Settings,
  Sun,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  Minus,
  AlertTriangle,
  ChevronRight,
  Filter,
  Download,
  Rss,
  Radar,
  Eye,
  Stethoscope,
  Leaf,
  Utensils,
  MemoryStick,
  Users,
  Database,
  ShieldCheck,
  Siren,
  Link2,
  Gauge,
  Radio,
  Zap,
  Store,
  FileText,
  CheckCircle2,
  Layers,
  Anchor,
  Waves,
  SunMedium,
  FlaskConical,
  Quote,
  CalendarDays,
  Target,
  Handshake,
  Building2,
  ExternalLink,
  Menu,
  X,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  public: Globe2,
  factory: Factory,
  analytics: BarChart3,
  precision_manufacturing: Cpu,
  location_on: MapPin,
  search: Search,
  notifications: Bell,
  settings: Settings,
  light_mode: Sun,
  sync: RefreshCw,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  trending_flat: Minus,
  warning: AlertTriangle,
  chevron_right: ChevronRight,
  filter_list: Filter,
  filter_alt: Filter,
  ios_share: Download,
  download: Download,
  rss_feed: Rss,
  radar: Radar,
  visibility: Eye,
  medical_services: Stethoscope,
  eco: Leaf,
  restaurant: Utensils,
  memory: MemoryStick,
  groups: Users,
  database: Database,
  shield_moon: ShieldCheck,
  verified: ShieldCheck,
  emergency: Siren,
  link: Link2,
  gas_meter: Gauge,
  sensors: Radio,
  bolt: Zap,
  shop: Store,
  description: FileText,
  check: CheckCircle2,
  layers: Layers,
  anchor: Anchor,
  waves: Waves,
  sun: SunMedium,
  science: FlaskConical,
  quote: Quote,
  calendar: CalendarDays,
  target: Target,
  handshake: Handshake,
  business: Building2,
  external_link: ExternalLink,
  menu: Menu,
  close: X,
};

export function Icon({
  name,
  className,
  size,
}: {
  name: string;
  className?: string;
  size?: number;
}) {
  const Cmp = ICONS[name] ?? Zap;
  return <Cmp className={className} size={size} />;
}
