import {
  DashboardData,
  GeopoliticalData,
  IndustrySummaryData,
  ProjectTrackerData,
  TechArticle,
} from "./types";
import { outletUrl } from "./outlets";

export const dashboardData: DashboardData = {
  kpis: [
    { label: "Geopolitical Risk", value: "HIGH", delta: "8 Critical Alerts Monitored", icon: "warning", tone: "danger" },
    { label: "Industry Status", value: "STABLE", delta: "Gas Sector Operations: Optimal", icon: "verified", tone: "accent" },
    { label: "Active Projects", value: "142", delta: "10 Countries | +12 this month", icon: "layers", tone: "neutral" },
    { label: "GC Opportunity Score", value: "8.2", delta: "3 High-yield leads", icon: "radar", tone: "accent" },
  ],
  geoPulse: [
    {
      tag: "WARNING",
      title: "Strait of Hormuz: Escalated Naval Presence Disrupts Energy Routes",
      source: "Al Jazeera - Middle East",
      sourceUrl: outletUrl("Al Jazeera - Middle East"),
      time: "1h ago",
    },
    {
      tag: "MONITOR",
      title: "UAE Hosts Emergency Summit on Middle East Stability Amid Escalating Tensions",
      source: "Khaleej Times - UAE",
      sourceUrl: outletUrl("Khaleej Times - UAE"),
      time: "2h ago",
    },
    {
      tag: "WARNING",
      title: "Red Sea: Houthi Maritime Disruptions Persist — Shipping Rerouted",
      source: "Arab News",
      sourceUrl: outletUrl("Arab News"),
      time: "4h ago",
    },
  ],
  industryWeekly: [
    {
      tag: "INVESTMENT",
      tone: "accent",
      title: "Air Products Secures $2.5bn Green Hydrogen Investment",
      desc: "Major expansion phase for Neom Hydrogen project reaches financial close with consortium backing.",
      source: "Gasworld",
      sourceUrl: outletUrl("Gasworld"),
      region: "MENA",
      image: "/photos/hydrogen-plant.jpg",
    },
    {
      tag: "ACQUISITION",
      tone: "cyan",
      title: "Linde Completes Acquisition of Gulf-Based Distributor",
      desc: "Strategic move strengthens market position in specialized medical gas supply chains.",
      source: "Gasworld",
      sourceUrl: outletUrl("Gasworld"),
      region: "MENA",
      image: "/photos/gas-cylinders.jpg",
    },
  ],
  leadershipMoves: [
    {
      company: "Air Liquide",
      initials: "AL",
      role: "New Regional President, Middle East & Africa",
      region: "MENA",
      desc: "Appointment consolidates decision-making closer to the region as competitors accelerate Gulf investment.",
      source: "Gasworld",
      sourceUrl: outletUrl("Gasworld"),
    },
    {
      company: "Messer",
      initials: "MS",
      role: "New VP of Industrial Gases, Gulf Operations",
      region: "MENA",
      desc: "Move follows Messer's expanded ASU footprint across Saudi Arabia and Kuwait.",
      source: "Gasworld",
      sourceUrl: outletUrl("Gasworld"),
    },
  ],
  marketSeries: [
    { label: "BRENT CRUDE (ICE)", value: "$84.12", change: "-0.8%", direction: "down", bars: [60, 80, 70, 50, 40, 45, 30] },
    { label: "HELIUM SPOT INDEX", value: "114.2", change: "+0.5%", direction: "up", bars: [40, 30, 50, 60, 75, 80, 90] },
  ],
  projectHighlights: [
    { title: "NEOM Hydrogen Phase 2", location: "Saudi Arabia • Q4 2026 Target", progress: 82, tone: "accent" },
    { title: "KIZAD Industrial Expansion", location: "UAE • Commissioning Phase", progress: 45, tone: "warning" },
    { title: "Basra Cryo-Hub Stage 1", location: "Iraq • Planning & Logistics", progress: 12, tone: "neutral" },
  ],
  opportunityRadar: [
    { code: "OM", country: "Oman", sector: "Gas Processing / LNG", tier: "High", potential: "2.1 BCM/Y potential" },
    { code: "BH", country: "Bahrain", sector: "Aluminum / Energy", tier: "High", potential: "0.8 BCM/Y potential" },
    { code: "QA", country: "Qatar", sector: "Speciality Gases / LNG", tier: "Moderate", potential: "1.4 BCM/Y potential" },
  ],
};

export const geopoliticalData: GeopoliticalData = {
  hotZone: {
    name: "Strait of Hormuz",
    coords: "26°34'N 56°15'E",
    lat: 26.57,
    lng: 56.25,
    detail: "Increased naval movement detected. Maritime traffic protocols elevated to Level 4.",
  },
  riskRegions: [
    { name: "MIDDLE EAST", pct: 92, tone: "danger" },
    { name: "CENTRAL EUROPE", pct: 45, tone: "warning" },
    { name: "INDO-PACIFIC", pct: 12, tone: "accent" },
  ],
  criticalIncident: {
    title: "Airspace Closure: Northern Levant",
    desc: "Multiple reports of kinetic action near civilian corridors. Flight path rerouting initiated for all Gulf Cryo logistics.",
    time: "04:12 UTC",
    lat: 36.2,
    lng: 37.0,
    source: "Al Jazeera",
    sourceUrl: outletUrl("Al Jazeera"),
  },
  countryRisk: [
    { country: "Saudi Arabia", lat: 24.7, lng: 46.7, tier: "moderate" },
    { country: "UAE", lat: 24.5, lng: 54.4, tier: "low" },
    { country: "Kuwait", lat: 29.4, lng: 47.9, tier: "moderate" },
    { country: "Bahrain", lat: 26.2, lng: 50.6, tier: "moderate" },
    { country: "Qatar", lat: 25.3, lng: 51.5, tier: "low" },
    { country: "Oman", lat: 23.6, lng: 58.5, tier: "low" },
    { country: "Jordan", lat: 31.9, lng: 35.9, tier: "moderate" },
    { country: "Iraq", lat: 33.3, lng: 44.4, tier: "high" },
    { country: "Turkey", lat: 39.9, lng: 32.9, tier: "moderate" },
    { country: "Egypt", lat: 30.0, lng: 31.2, tier: "moderate" },
  ],
  articles: [
    {
      tag: "MONITOR",
      region: "MIDDLE EAST",
      time: "1h ago",
      title: "Strait of Hormuz: Escalated Naval Presence Disrupts Energy Routes",
      desc: "Significant increase in maritime traffic blocking protocols. Risk to energy supply chains reaching Tier-1 threshold. Sources indicate deployment of additional offshore assets.",
      source: "Al Jazeera",
      sourceUrl: outletUrl("Al Jazeera"),
    },
    {
      tag: "WARNING",
      region: "UAE",
      time: "2h ago",
      title: "UAE Hosts Emergency Summit on Middle East Stability Amid Escalating Tensions",
      desc: "The UAE facilitated high-level talks focusing on de-escalation efforts and humanitarian access in active conflict zones. Global energy leaders present at the closed-door meeting.",
      source: "Khaleej Times",
      sourceUrl: outletUrl("Khaleej Times"),
    },
    {
      tag: "WARNING",
      region: "RED SEA",
      time: "3h ago",
      title: "Red Sea: Houthi Maritime Disruptions Persist — Shipping Rerouted",
      desc: "Shipping companies rerouting vessels around the Cape of Good Hope, adding significant cost and transit time. Impact on helium logistics expected within 72 hours.",
      source: "Al Jazeera",
      sourceUrl: outletUrl("Al Jazeera"),
    },
    {
      tag: "MONITOR",
      region: "SAUDI ARABIA",
      time: "4h ago",
      title: "Saudi Arabia Calls for Unified Arab Response to Regional Security Threats",
      desc: "Riyadh urged coordinated action among Gulf nations as geopolitical pressures intensify. Focus on protecting regional energy infrastructure from cyber and physical threats.",
      source: "Arab News",
      sourceUrl: outletUrl("Arab News"),
    },
  ],
};

export const industrySummaryData: IndustrySummaryData = {
  competitors: [
    {
      country: "Saudi Arabia",
      linde: { value: "Strong", tone: "danger" },
      airProducts: { value: "Dominant", tone: "danger" },
      airLiquide: { value: "Strong", tone: "danger" },
      messer: { value: "Limited", tone: "accent" },
      gcOpportunity: { value: "Contested", tone: "danger" },
    },
    {
      country: "UAE",
      linde: { value: "Dominant", tone: "danger" },
      airProducts: { value: "Active", tone: "accent" },
      airLiquide: { value: "Strong", tone: "danger" },
      messer: { value: "Active", tone: "accent" },
      gcOpportunity: { value: "Contested", tone: "danger" },
    },
    {
      country: "Qatar",
      linde: { value: "Active", tone: "accent" },
      airProducts: { value: "Strong", tone: "danger" },
      airLiquide: { value: "Active", tone: "accent" },
      messer: { value: "Limited", tone: "accent" },
      gcOpportunity: { value: "Moderate", tone: "warning" },
    },
    {
      country: "Kuwait",
      linde: { value: "Strong", tone: "danger" },
      airProducts: { value: "Active", tone: "accent" },
      airLiquide: { value: "Active", tone: "accent" },
      messer: { value: "Limited", tone: "accent" },
      gcOpportunity: { value: "Moderate", tone: "warning" },
    },
    {
      country: "Oman",
      linde: { value: "Active", tone: "accent" },
      airProducts: { value: "Active", tone: "accent" },
      airLiquide: { value: "Limited", tone: "accent" },
      messer: { value: "Limited", tone: "accent" },
      gcOpportunity: { value: "High", tone: "accent" },
    },
  ],
  opportunities: [
    {
      code: "OM",
      country: "Oman",
      sector: "Gas Processing / LNG",
      score: 92,
      summary: "All major competitors have LIMITED presence. Gas processing & LNG sector growing rapidly with no dominant incumbent.",
      actionUrgency: "IMMEDIATE",
      action: "Initiate market entry — bulk gas distribution & ASU",
      potential: "2.1 BCM/y potential",
      progress: 78,
    },
    {
      code: "BH",
      country: "Bahrain",
      sector: "Aluminum / Energy",
      score: 88,
      summary: "No dominant competitor. ALBA aluminum complex requires large nitrogen volumes. GC has UAE logistics advantage.",
      actionUrgency: "IMMEDIATE",
      action: "Target ALBA aluminum complex supply contract",
      potential: "0.8 BCM/y potential",
      progress: 65,
    },
    {
      code: "JO",
      country: "Jordan",
      sector: "Phosphate / Mining",
      score: 85,
      summary: "All competitors LIMITED or absent. Phosphate & mining sector underserved. GC foothold present — expand.",
      actionUrgency: "SHORT-TERM",
      action: "Expand distribution & add ASU capacity near Aqaba",
      potential: "0.6 BCM/y potential",
      progress: 52,
    },
  ],
  whiteSpace: [
    {
      icon: "medical_services",
      tier: "HIGH",
      tone: "accent",
      title: "Medical & Healthcare",
      desc: "Fragmented — no dominant player across ME hospitals. High margin clinical grade gases.",
      angle: "Hospital O₂ pipeline systems & N₂O supply",
    },
    {
      icon: "eco",
      tier: "HIGH",
      tone: "accent",
      title: "Green Hydrogen",
      desc: "Air Products focuses on H₂ — O₂ co-product underutilised. Massive electrolysis scale-up.",
      angle: "Capture & distribute O₂ from electrolysis plants",
    },
    {
      icon: "restaurant",
      tier: "MEDIUM",
      tone: "warning",
      title: "Food & Beverage CO₂",
      desc: "Minimal structured presence across 10 countries. Direct to consumer bottling supply.",
      angle: "CO₂ & N₂ for food preservation & carbonation",
    },
    {
      icon: "memory",
      tier: "EMERGING",
      tone: "cyan",
      title: "Electronics / Semi",
      desc: "Niche — minimal GCC presence by any major player. High purity gas requirement.",
      angle: "Ultra-high purity gases for Saudi & UAE fabs",
    },
  ],
};

export const projectTrackerData: ProjectTrackerData = {
  kpis: [
    { label: "ACTIVE PROJECTS", value: "142", delta: "+12 THIS MONTH", icon: "groups", tone: "neutral" },
    { label: "PROJECTED DEMAND", value: "42.8", suffix: "BCM/Y", delta: "AGGREGATED REGIONAL", icon: "database", tone: "neutral" },
    { label: "SUSTAINABILITY INDEX", value: "84%", delta: "ABOVE BASELINE", icon: "eco", tone: "accent" },
    { label: "SYSTEM ALERTS", value: "03", delta: "REQUIRING ACTION", icon: "warning", tone: "danger" },
  ],
  projects: [
    {
      title: "NEOM Green Hydrogen Phase 2",
      location: "Tabuk Region, KSA",
      status: "IN PROGRESS",
      statusTone: "accent",
      gasDemand: "3.2 BCM/Y",
      innovation: "Electrolyzer V4",
      quote: "Grid synchronization completed. Pipe laying at 84% capacity.",
      atcConnection: true,
      icon: "eco",
      category: "renewable",
    },
    {
      title: "Dubai Smart Port Logistics",
      location: "Jebel Ali, UAE",
      status: "PLANNING",
      statusTone: "warning",
      gasDemand: "1.8 BCM/Y",
      innovation: "Edge AI Load",
      quote: "Environmental impact assessment approved. Review Wednesday.",
      atcConnection: false,
      icon: "anchor",
      image: "/photos/shipping-port.jpg",
      category: "construction",
    },
    {
      title: "Doha Desalination Hub",
      location: "Coastal Sector, Qatar",
      status: "OPERATIONAL",
      statusTone: "cyan",
      gasDemand: "2.4 BCM/Y",
      innovation: "Nano-Filter X",
      quote: "Full capacity reached. Telemetry integrated with ATC.",
      atcConnection: true,
      icon: "waves",
      category: "sustainability",
    },
    {
      title: "Red Sea Solar Initiative",
      location: "Red Sea Coast, Egypt",
      status: "DELAYED",
      statusTone: "danger",
      gasDemand: "0.5 BCM/Y",
      innovation: "Solar-Gas Hybrid",
      quote: "PV module delay sector 7. ATC demand rerouted.",
      atcConnection: false,
      icon: "sun",
      image: "/photos/solar-desert.jpg",
      category: "renewable",
    },
  ],
  territories: [
    { country: "Saudi Arabia", projects: 42, innovationPct: 90, sector: "Hydrogen / Infrastructure", opportunity: "HIGH", trend: "up" },
    { country: "United Arab Emirates", projects: 31, innovationPct: 80, sector: "Logistics / Smart Grid", opportunity: "HIGH", trend: "up" },
    { country: "Egypt", projects: 18, innovationPct: 45, sector: "Solar / Industrial", opportunity: "MEDIUM", trend: "flat" },
    { country: "Qatar", projects: 14, innovationPct: 60, sector: "LNG / Water Distribution", opportunity: "HIGH", trend: "up" },
    { country: "Jordan", projects: 7, innovationPct: 20, sector: "Phosphate / Mining", opportunity: "EMERGING", trend: "down" },
  ],
};

export const techArticles: TechArticle[] = [
  {
    tag: "Hydrogen",
    tone: "cyan",
    time: "1d ago",
    title: "Green Hydrogen Electrolyzer Costs Fall 40% Year-on-Year as Scale Increases",
    desc: "Advanced PEM electrolyzer technology achieves record efficiency with costs approaching parity with grey hydrogen. Scaling manufacturing facilities in Kuwait and UAE are primary drivers for this deflationary trend.",
    source: "H2 View",
    sourceUrl: outletUrl("H2 View"),
    size: "featured",
    icon: "description",
    region: "MENA",
  },
  {
    tag: "Renewable",
    tone: "accent",
    time: "2d ago",
    title: "Saudi Arabia's 650MW Solar-Powered ASU Sets New Sustainability Benchmark",
    desc: "Fully renewable-powered air separation unit representing major step toward net-zero industrial gas production.",
    source: "Renewables Now",
    sourceUrl: outletUrl("Renewables Now"),
    size: "standard",
    icon: "rss_feed",
    region: "MENA",
  },
  {
    tag: "CCS/CCU",
    tone: "warning",
    time: "3d ago",
    title: "Industrial Gas CCS Deployment Accelerates Across GCC — New Benchmarks Set",
    desc: "Industrial gas companies leading carbon capture innovation with new liquid CO₂ transport solutions across the peninsula.",
    source: "Gasworld",
    sourceUrl: outletUrl("Gasworld"),
    size: "standard",
    icon: "bolt",
    region: "MENA",
  },
  {
    tag: "Innovation",
    tone: "cyan",
    time: "4d ago",
    title: "IoT Cylinder Tracking Technology Cuts Industrial Gas Losses by 28%",
    desc: "Digital telemetry and predictive maintenance platforms helping distributors reduce losses across fleets through real-time sensors.",
    source: "Gasworld Fleet Insight",
    sourceUrl: outletUrl("Gasworld Fleet Insight"),
    size: "wide",
    icon: "sensors",
    region: "Americas",
  },
  {
    tag: "Renewable",
    tone: "accent",
    time: "5d ago",
    title: "Wind-Powered Nitrogen Production Pilot Launches in Oman — A GCC First",
    desc: "Pilot facility uses offshore wind to power ASU, demonstrating viability of fully renewable industrial gases in maritime hubs.",
    source: "Renewables Now",
    sourceUrl: outletUrl("Renewables Now"),
    size: "half",
    icon: "eco",
    region: "MENA",
  },
  {
    tag: "Hydrogen",
    tone: "cyan",
    time: "6d ago",
    title: "Liquid Hydrogen Supply Chain Advances as Shipping Infrastructure Scales",
    desc: "New liquefaction and cryogenic transport vessels enter service supporting long-distance hydrogen export from Saudi to European markets.",
    source: "H2 View Global",
    sourceUrl: outletUrl("H2 View Global"),
    size: "half",
    region: "Europe",
    icon: "shop",
  },
  {
    tag: "Hydrogen",
    tone: "cyan",
    time: "7d ago",
    title: "Singapore Launches Regional Hydrogen Bunkering Pilot for Maritime Fuel Transition",
    desc: "Port-based pilot tests ship-to-ship hydrogen bunkering protocols, positioning the city-state as a Southeast Asian refuelling hub for low-carbon shipping.",
    source: "Gasworld",
    sourceUrl: outletUrl("Gasworld"),
    size: "standard",
    icon: "anchor",
    region: "ASEAN",
  },
];
