import { DispatchData } from "./types";

export const mockDispatchData: DispatchData = {
  date: "2026-07-21",
  generated_at: "2026-07-21T03:00:00Z",
  kpi: {
    geopolitical: {
      label: "Geopolitical Risk",
      value: "Elevated",
      color: "error",
      footer_text: "SCORE: 8.1/10 (Critical Zones: Red Sea, Southern Iran)",
      progress: 81,
    },
    industry: {
      label: "Industry Stability",
      value: "Stressed",
      color: "primary",
      footer_text: "SUPPLY CHAIN INDEX: 58.2 (Helium Constrained)",
      progress: 45,
    },
    projects: {
      label: "Project Growth",
      value: "Active",
      color: "tertiary",
      footer_text: "CAPEX VELOCITY: +6.8% MoM",
      progress: 68,
    },
  },
  alerts: [
    {
      tag: "Geopolitical / Red Sea",
      tag_color: "error",
      time: "05:40 UTC",
      title: "Houthi naval blockade tightens around Saudi Red Sea ports",
      desc: "Shipping insurers widen war-risk zones off Jeddah and Yanbu; tanker traffic rerouting via Cape of Good Hope adds 10-14 days to GCC-bound cargo.",
      source_url: "https://www.reuters.com/world/middle-east/",
    },
    {
      tag: "Security / Iran",
      tag_color: "error",
      time: "02:15 UTC",
      title: "US strikes reported on targets in southern Iran",
      desc: "Strikes reported near energy infrastructure in Bushehr province; regional markets pricing in elevated Strait of Hormuz transit risk.",
      source_url: "https://www.aljazeera.com/where/iran/",
    },
    {
      tag: "Diplomacy / Regional",
      tag_color: "primary",
      time: "Yesterday",
      title: "10-day ceasefire proposal circulated among regional mediators",
      desc: "Qatari and Omani channels reportedly floated a 10-day truce framework; no confirmation from involved parties as of this morning.",
      source_url: "https://www.reuters.com/world/middle-east/",
    },
    {
      tag: "Diplomacy / Lebanon",
      tag_color: "primary",
      time: "Yesterday",
      title: "Lebanon's President Aoun meets Trump on sidelines of regional summit",
      desc: "Talks reportedly covered southern Lebanon security arrangements and reconstruction financing tied to Gulf donor commitments.",
      source_url: "https://apnews.com/hub/lebanon",
    },
  ],
  markets: [
    { exchange: "ADX (Abu Dhabi)", latest: "9,782.00", move: "+0.45%", direction: "up" },
    { exchange: "DFM (Dubai)", latest: "5,214.30", move: "+1.13%", direction: "up" },
    { exchange: "TASI (Saudi)", latest: "10,819.00", move: "+0.10%", direction: "up" },
    { exchange: "QSE (Qatar)", latest: "10,090.00", move: "-1.18%", direction: "down" },
    { exchange: "Kuwait (Premier)", latest: "9,082.00", move: "-0.10%", direction: "down" },
    { exchange: "MSX (Oman)", latest: "7,652.00", move: "+0.10%", direction: "up" },
    { exchange: "BHB (Bahrain)", latest: "2,011.00", move: "+0.10%", direction: "up" },
    { exchange: "EGX 30 (Egypt)", latest: "52,928.00", move: "+0.70%", direction: "up" },
  ],
  energy: [
    {
      title: "Brent crosses $90 as Red Sea risk premium builds",
      desc: "Brent trading $88-89/bbl on sustained Red Sea disruption and Strait of Hormuz risk premium; WTI tracking roughly $4 below.",
      source_url: "https://www.reuters.com/business/energy/",
    },
    {
      title: "Global helium supply 30-38% offline",
      desc: "Combined outages across US BLM reserve, Qatari, and Russian sources have pulled 30-38% of global helium capacity offline; spot pricing up sharply quarter-over-quarter.",
      source_url: "https://www.gasworld.com/",
    },
    {
      title: "ADNOC consolidates LNG trading under unified desk",
      desc: "ADNOC has unified its LNG trading operations into a single desk ahead of Ruwais LNG's first cargoes, aiming for tighter portfolio optimization.",
      source_url: "https://www.adnoc.ae/en/news-and-media",
    },
  ],
  business: [
    {
      tag: "Regulatory / UAE",
      tag_color: "primary",
      time: "Deadline: Jul 30",
      title: "UAE Competition Law compliance deadline approaches",
      desc: "Businesses have until July 30 to complete merger notification and market-dominance self-assessments under the amended Competition Law.",
      source_url: "https://u.ae/en/about-the-uae/legislation",
    },
    {
      tag: "Labor / UAE",
      tag_color: "primary",
      time: "Ongoing",
      title: "Emiratisation wage floor takes effect for target sectors",
      desc: "New minimum wage floor for UAE national hires under Emiratisation quotas now binding for firms above headcount thresholds.",
      source_url: "https://www.mohre.gov.ae/en/",
    },
    {
      tag: "Regulatory / Saudi",
      tag_color: "error",
      time: "Deadline: Aug 6",
      title: "Saudi Qiwa contract-documentation deadline set for Aug 6",
      desc: "All active employment contracts must be digitized and confirmed on the Qiwa platform by August 6 or face registration holds.",
      source_url: "https://qiwa.sa/",
    },
    {
      tag: "Economic / Outlook",
      tag_color: "tertiary",
      time: "This week",
      title: "Saudi & UAE Q3 non-oil growth outlook revised upward",
      desc: "Both central banks flag resilient non-oil sector growth for Q3 despite regional security headlines, citing construction and logistics strength.",
      source_url: "https://www.centralbank.ae/en/",
    },
  ],
  gulfcryo: [
    {
      icon: "warning",
      icon_color: "error",
      title: "Helium crisis pressures specialty gas margins",
      desc: "Global helium shortage is compressing margins on specialty gas contracts; procurement team evaluating alternate sourcing from North African suppliers.",
    },
    {
      icon: "handshake",
      icon_color: "tertiary",
      title: "EMSTEEL partnership advances CO2 capture expansion",
      desc: "Joint CO2 recovery expansion with EMSTEEL progressing on schedule; supports GulfCryo's food & beverage grade CO2 supply commitments in the UAE.",
    },
    {
      icon: "route",
      icon_color: "primary",
      title: "Dual-chokepoint exposure flagged on Red Sea + Hormuz routes",
      desc: "Combined Red Sea and Strait of Hormuz disruptions create compounding supply chain risk for cross-regional cylinder and bulk logistics.",
    },
  ],
  weekly: {
    industry: [
      {
        tag: "Market / Growth",
        tag_color: "tertiary",
        time: "This week",
        title: "ME industrial gas market projected to grow from $10.1B to $12.7B by 2032",
        desc: "Analysts cite hydrogen, CCUS, and on-site generation demand as primary growth drivers across the region through the forecast period.",
        source_url: "https://www.gasworld.com/",
      },
      {
        tag: "Capital / M&A",
        tag_color: "primary",
        time: "This week",
        title: "Linde, Air Liquide, and Air Products accelerate regional capital deployment",
        desc: "All three majors have announced incremental ME capex this quarter, focused on on-site generation plants tied to steel and refining expansions.",
        source_url: "https://www.linde.com/news-media",
      },
      {
        tag: "Leadership",
        tag_color: "primary",
        time: "This week",
        title: "Regional leadership appointments signal renewed ME investment focus",
        desc: "Multiple majors have named new regional VPs for the Middle East this quarter, consolidating decision-making closer to the region.",
        source_url: "https://www.airliquide.com/",
      },
      {
        tag: "Technology",
        tag_color: "tertiary",
        time: "This week",
        title: "CCUS and on-site generation dominate new project announcements",
        desc: "The majority of new industrial gas project announcements this week are tied to carbon capture or on-site generation rather than merchant supply.",
        source_url: "https://www.gasworld.com/",
      },
    ],
    projects: [
      {
        country_tags: ["KSA"],
        title: "NEOM Green Hydrogen Phase 2 financing close",
        status: "In Progress",
        desc: "Lenders finalizing Phase 2 debt package for the NEOM green hydrogen facility, targeting first production in the next 18 months.",
        atc_relevance: "Direct alignment with hydrogen separation and purification workstream at SPARK.",
        source_url: "https://www.neom.com/en-us/newsroom",
      },
      {
        country_tags: ["KSA"],
        title: "Gulf Cryo-Aramco H2 & CCUS center at SPARK advances design phase",
        status: "In Progress",
        desc: "Joint ATC design phase for hydrogen and CCUS pilot lines moving toward FEED (front-end engineering design) stage.",
        atc_relevance: "Core project — this is the ATC's flagship hydrogen/CCUS initiative.",
        source_url: "https://www.aramco.com/en/news-media",
      },
      {
        country_tags: ["QAT"],
        title: "Qatar North Field East (NFE) expansion on schedule",
        status: "In Progress",
        desc: "NFE LNG train construction remains on schedule for next-year startup, reinforcing Qatar's position as top LNG exporter.",
        atc_relevance: "Indirect — supports regional gas feedstock availability relevant to industrial gas supply planning.",
        source_url: "https://www.qatarenergy.qa/en/MediaCenter",
      },
      {
        country_tags: ["UAE"],
        title: "ADNOC Ruwais LNG nears first cargo milestone",
        status: "In Progress",
        desc: "Ruwais LNG construction entering commissioning phase, with first cargoes expected within the quarter.",
        atc_relevance: "Indirect — relevant to UAE gas market dynamics and ADNOC's broader industrial gas footprint.",
        source_url: "https://www.adnoc.ae/en/news-and-media",
      },
      {
        country_tags: ["JOR"],
        title: "Aqaba desalination-to-industrial water project breaks ground",
        status: "Scheduled",
        desc: "New desalination capacity earmarked partly for industrial users in the Aqaba Special Economic Zone.",
        atc_relevance: "Low direct relevance — monitored for regional industrial water/utility cost trends.",
        source_url: "https://www.jordantimes.com/",
      },
      {
        country_tags: ["IRQ"],
        title: "Iraq steel sector expansion plans announced",
        status: "Scheduled",
        desc: "State-backed steel expansion plans announced for Basra region, with industrial gas supply agreements expected to follow.",
        atc_relevance: "Medium — potential future merchant gas demand growth in southern Iraq.",
        source_url: "https://www.iraq-businessnews.com/",
      },
      {
        country_tags: ["EGY"],
        title: "Egypt-Turkey $7B industrial zone announced",
        status: "In Progress",
        desc: "Bilateral agreement establishes a joint industrial zone targeting manufacturing and logistics investment of $7B over five years.",
        atc_relevance: "Low — tracked for potential North African gas market expansion opportunities.",
        source_url: "https://www.reuters.com/world/middle-east/",
      },
      {
        country_tags: ["KSA", "UAE"],
        title: "Regional solar capacity pipeline reaches 30 GW",
        status: "In Progress",
        desc: "Combined Saudi and UAE utility-scale solar pipeline crosses 30 GW, feeding growing green hydrogen ambitions region-wide.",
        atc_relevance: "Medium — supports renewable power availability for green hydrogen production pathways.",
        source_url: "https://www.irena.org/News",
      },
      {
        country_tags: ["KSA", "UAE", "QAT"],
        title: "CCUS project scaling accelerates across the Gulf",
        status: "In Progress",
        desc: "Multiple CCUS pilot-to-commercial scale-ups announced this week across Saudi, UAE, and Qatari industrial hubs.",
        atc_relevance: "Direct — core to the ATC's CCUS technology roadmap and pilot validation work.",
        source_url: "https://www.gasworld.com/",
      },
    ],
  },
  strategic_alert:
    "Dual-chokepoint exposure on Red Sea and Strait of Hormuz routes warrants immediate review of cylinder and bulk logistics contingency routing. Prioritize alternate sourcing discussions for helium given sustained 30-38% global supply outage, and align ATC hydrogen/CCUS workstream timelines with the Gulf Cryo-Aramco SPARK design-phase milestones.",
  sources: [
    { title: "Reuters — Middle East", url: "https://www.reuters.com/world/middle-east/" },
    { title: "Al Jazeera — Iran", url: "https://www.aljazeera.com/where/iran/" },
    { title: "AP News — Lebanon", url: "https://apnews.com/hub/lebanon" },
    { title: "Reuters — Energy", url: "https://www.reuters.com/business/energy/" },
    { title: "Gasworld", url: "https://www.gasworld.com/" },
    { title: "ADNOC Newsroom", url: "https://www.adnoc.ae/en/news-and-media" },
    { title: "UAE Government Portal", url: "https://u.ae/en/about-the-uae/legislation" },
    { title: "MOHRE (UAE)", url: "https://www.mohre.gov.ae/en/" },
    { title: "Qiwa (Saudi)", url: "https://qiwa.sa/" },
    { title: "Central Bank of the UAE", url: "https://www.centralbank.ae/en/" },
    { title: "Linde Newsroom", url: "https://www.linde.com/news-media" },
    { title: "Air Liquide", url: "https://www.airliquide.com/" },
    { title: "NEOM Newsroom", url: "https://www.neom.com/en-us/newsroom" },
    { title: "Aramco Newsroom", url: "https://www.aramco.com/en/news-media" },
    { title: "Qatar Energy Media Center", url: "https://www.qatarenergy.qa/en/MediaCenter" },
    { title: "Jordan Times", url: "https://www.jordantimes.com/" },
    { title: "Iraq Business News", url: "https://www.iraq-businessnews.com/" },
    { title: "IRENA News", url: "https://www.irena.org/News" },
  ],
};
